name = "wordpress-site-health-analyzer"
main = "src/index.ts"
compatibility_date = "2023-10-25"

[[d1_databases]]
binding = "DB"
database_name = "site-health-analytics"
database_id = "896b3550-f29f-4a5c-9e1d-221a08a9f4bf"

[vars]
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD_HASH = "240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9"

[env.production]
name = "wordpress-site-health-analyzer"

[env.development]
name = "wordpress-site-health-analyzer-dev"
